### ISSUE TITLE
Predicate fd_domain/3 not defined

### ISSUE THREAD

**Issue by ahmadalzoubi13579** [Tordesillas/Prolog-Nurikabe#1]
hey guys:
when i run the code i get this error:

![untitled](https://user-images.githubusercontent.com/33967218/40874877-2a9c3b48-667e-11e8-8639-ae8ec57aff1e.png)

Any Help :)

**Comment by gogoIsComing** [comment]
i was running this code on swi-prolog i just switched to GNU prolog and there is no warnings

**Comment by ahmadalzoubi13579** [comment]
i was running this code on swi-prolog i just switched to GNU prolog and there is no warnings

**Comment by ahmadalzoubi13579** [comment]
i run it on GNU prolog but there is no output , Maybe because the algorithm has exponential complexity
